### ISSUE TITLE
G4H is different from the example

### ISSUE THREAD

**Issue by atlasbioinfo** [odoluca/G4Catchall#1]
```

cat test.fa
>testfa
TTGGGTTGGGACTGGGTACGGGAATAAATAGGTTAGGAATGGATAGGAT

python G4Catchall.py -f test.fa --G3L 1..3 --G4H

testfa  2       22      20      +       GGGTTGGGACTGGGTACGGG    GGGTTGGGACTGGGTACGGG    0.45
```
While the G4H in the example is 2.11.

**Comment by odoluca** [comment]
The issue is acknowledged. I am working on it. I apologize for the inconvenience.

**Comment by odoluca** [comment]
The error is fixed. In the G4Hunter calculation the number of repeats were not multiplied by itself. 
I apologize and thank you repeeatedly. All should be sorted now.
